### ISSUE TITLE
Kernel appears to have died. 

### ISSUE THREAD

**Issue by rosalierazonable** [kearnz/autoimpute#75]
Hi! 

I would like to ask why it would return "Kernel restarting" on my end whenever I use autoimputer? 
I simply just wanna try out the simple MiceImputer Imputation before I actually use it. 

`from autoimpute.imputations import MiceImputer
imp = MiceImputer()
imp.fit_transform(data)`

I am relatively new to python so I would really appreciate your response.

**Comment by kearnz** [comment]
Hi @rosalierazonable,

Hard to know what the problem is without more information. Could be an issue with package dependencies or versions, unsupported/missing libraries, or compute/memory issues (if you're running on a very large dataset).

Can you run the same code in a simple python script without issue?

Joe

**Comment by rosalierazonable** [comment]
Hi @kearnz, 

Thank you for responding. I actually have 41,615 data records with 44 variables. 
I just simply want to try out and see whether the library works on my system.

Also, if it helps these are the distribution of my data:

object     20
float64    13
bool       13
int64       1

**Comment by kearnz** [comment]
Hi - it's really hard to say w/o understanding your dataset or your system, but I'd imagine that the kernel is dying because the program is consuming too much memory. 

By default, you'd be running bayesian methods on every column, using every other column. That's going to be quite intensive for one single machine. 

I'd see if things work on a subset of the rows & columns, then scale from there as needed.
